const fetch = require('node-fetch');
const config = require('../config');

function hasKey(val) {
  return Boolean(val && val.trim() && !val.includes('your_') && !val.includes('placeholder'));
}

async function isOllamaReachable() {
  try {
    const res = await fetch(`${config.ollamaHost}/api/tags`, { timeout: 1500 });
    return res.ok;
  } catch {
    return false;
  }
}

async function detectActiveProvider() {
  const chosen = (config.llmProvider || 'auto').toLowerCase();

  if (chosen === 'gemini') return 'gemini';
  if (chosen === 'ollama') return 'ollama';
  if (chosen === 'anthropic') return 'anthropic';

  // In 'auto' mode, prioritize Gemini (free tier), then local Ollama (free local), then Anthropic
  if (hasKey(config.geminiApiKey)) {
    return 'gemini';
  }

  if (await isOllamaReachable()) {
    return 'ollama';
  }

  if (hasKey(config.anthropicApiKey)) {
    return 'anthropic';
  }

  return null;
}

function extractJson(text) {
  if (!text) throw new Error('Model returned empty response');
  const cleaned = text.replace(/```json|```/g, '').trim();
  const startArr = cleaned.indexOf('[');
  const startObj = cleaned.indexOf('{');

  let start = -1;
  let end = -1;

  if (startArr !== -1 && (startObj === -1 || startArr < startObj)) {
    start = startArr;
    end = cleaned.lastIndexOf(']');
  } else if (startObj !== -1) {
    start = startObj;
    end = cleaned.lastIndexOf('}');
  }

  if (start === -1 || end === -1) {
    throw new Error(`Model response did not contain valid JSON: ${text.slice(0, 100)}...`);
  }

  return JSON.parse(cleaned.slice(start, end + 1));
}

// 1. Google Gemini API Call (Free tier at https://aistudio.google.com/)
async function callGemini(prompt) {
  if (!hasKey(config.geminiApiKey)) {
    throw new Error(
      'GEMINI_API_KEY is not set. Get a free key at https://aistudio.google.com/ and add GEMINI_API_KEY=... to backend/.env'
    );
  }

  const candidateModels = [
    config.geminiModel,
    'gemini-3.6-flash',
    'gemini-flash-lite-latest',
    'gemini-flash-latest',
  ].filter(Boolean);
  const uniqueModels = [...new Set(candidateModels)];

  let lastError = null;

  for (const model of uniqueModels) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${config.geminiApiKey}`;

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            responseMimeType: 'application/json',
          },
        }),
      });

      if (!response.ok) {
        const errBody = await response.text();
        if (response.status === 503 || response.status === 429 || response.status === 404) {
          console.warn(`[Gemini] Model ${model} returned ${response.status}, attempting fallback model...`);
          lastError = new Error(`Google Gemini API error (${response.status}): ${errBody}`);
          continue;
        }
        throw new Error(`Google Gemini API error (${response.status}): ${errBody}`);
      }

      const data = await response.json();
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) throw new Error('No text generated by Gemini');
      return extractJson(text);
    } catch (err) {
      lastError = err;
      if (err.message.includes('503') || err.message.includes('429') || err.message.includes('404')) {
        continue;
      }
      throw err;
    }
  }

  throw lastError || new Error('All Gemini candidate models failed');
}

// 2. Local Ollama Call (100% free & offline on Mac)
async function callOllama(prompt) {
  const url = `${config.ollamaHost}/api/generate`;

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: config.ollamaModel,
      prompt,
      stream: false,
      format: 'json',
    }),
  });

  if (!response.ok) {
    const errBody = await response.text();
    throw new Error(`Local Ollama error (${response.status}): ${errBody}`);
  }

  const data = await response.json();
  return extractJson(data.response);
}

// 3. Anthropic Claude API Call
async function callAnthropic(prompt) {
  if (!hasKey(config.anthropicApiKey)) {
    throw new Error(
      'ANTHROPIC_API_KEY is not set. Add ANTHROPIC_API_KEY=... to backend/.env or use a free Google Gemini key'
    );
  }

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': config.anthropicApiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: config.anthropicModel,
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Anthropic API error (${response.status}): ${body}`);
  }

  const data = await response.json();
  const textBlock = (data.content || []).find((b) => b.type === 'text');
  if (!textBlock) throw new Error('No text content returned from Anthropic model');
  return extractJson(textBlock.text);
}

/**
 * Generate JSON output using the detected active LLM provider.
 */
async function generateJson(prompt) {
  const provider = await detectActiveProvider();

  if (!provider) {
    throw new Error(
      'No AI provider configured! To enable viral moment extraction and AI descriptions, either:\n' +
      '1. (Recommended Free) Add a free Google Gemini key: GEMINI_API_KEY=your_key in backend/.env (Get one at https://aistudio.google.com/)\n' +
      '2. (Free Local) Start Ollama locally: "ollama run llama3.2"\n' +
      '3. Add an Anthropic key: ANTHROPIC_API_KEY=your_key in backend/.env'
    );
  }

  console.log(`[LLM Client] Using AI provider: ${provider.toUpperCase()}`);

  if (provider === 'gemini') {
    return await callGemini(prompt);
  } else if (provider === 'ollama') {
    return await callOllama(prompt);
  } else {
    return await callAnthropic(prompt);
  }
}

async function getProviderStatus() {
  const active = await detectActiveProvider();
  const ollamaOk = await isOllamaReachable();

  return {
    activeProvider: active,
    configuredProviderSetting: config.llmProvider,
    providers: {
      gemini: {
        isConfigured: hasKey(config.geminiApiKey),
        model: config.geminiModel,
        tier: 'Free Tier Available (Google AI Studio)',
      },
      ollama: {
        isReachable: ollamaOk,
        host: config.ollamaHost,
        model: config.ollamaModel,
        tier: '100% Free & Local',
      },
      anthropic: {
        isConfigured: hasKey(config.anthropicApiKey),
        model: config.anthropicModel,
        tier: 'Paid / Free Trial Credits',
      },
    },
  };
}

module.exports = {
  detectActiveProvider,
  generateJson,
  getProviderStatus,
};
